import { VideoMetadata, VideoCategory } from '@/app/types/video';

export const VIDEO_CATEGORIES: VideoCategory[] = [
  'All',
  'Gaming',
  'Music',
  'Technology',
  'Science',
  'Education',
  'Entertainment',
  'News',
  'Sports',
  'Travel',
  'Cooking',
  'Fashion',
  'Art',
];

export const MOCK_VIDEOS: VideoMetadata[] = [
  {
    id: '1',
    title: 'The Future of Artificial Intelligence: Ethics and Advancements',
    description: 'An in-depth look at the current state of AI, future developments, and the ethical considerations we need to address as this technology continues to evolve.',
    thumbnailUrl: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg',
    videoUrl: 'https://example.com/videos/ai-future.mp4',
    duration: 985, // 16:25
    views: 1254789,
    likes: 87420,
    dislikes: 2145,
    uploadDate: '2023-07-15',
    verified: true,
    channel: {
      id: 'c1',
      name: 'TechInsights',
      avatarUrl: 'https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg',
      subscribers: 2450000,
      verified: true,
    },
    category: 'Technology',
    tags: ['AI', 'technology', 'ethics', 'future tech'],
  },
  {
    id: '2',
    title: 'Quantum Computing Explained Simply',
    description: 'A beginner-friendly explanation of quantum computing concepts, including qubits, superposition, and how quantum computers will change our world.',
    thumbnailUrl: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg',
    videoUrl: 'https://example.com/videos/quantum-computing.mp4',
    duration: 1247, // 20:47
    views: 987654,
    likes: 65432,
    dislikes: 1234,
    uploadDate: '2023-08-22',
    verified: true,
    channel: {
      id: 'c2',
      name: 'Science Simplified',
      avatarUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
      subscribers: 1750000,
      verified: true,
    },
    category: 'Science',
    tags: ['quantum', 'physics', 'computing', 'science'],
  },
  {
    id: '3',
    title: 'Ambient Lo-Fi Beats for Studying and Relaxation',
    description: 'A curated mix of lo-fi hip hop beats perfect for studying, working, or relaxing. Enjoy these smooth, chill vibes to help you focus or unwind.',
    thumbnailUrl: 'https://images.pexels.com/photos/1626481/pexels-photo-1626481.jpeg',
    videoUrl: 'https://example.com/videos/lofi-beats.mp4',
    duration: 3600, // 1:00:00
    views: 4578932,
    likes: 189562,
    dislikes: 3241,
    uploadDate: '2023-05-10',
    verified: false,
    channel: {
      id: 'c3',
      name: 'ChillBeats Studio',
      avatarUrl: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg',
      subscribers: 3250000,
      verified: false,
    },
    category: 'Music',
    tags: ['lofi', 'hiphop', 'study music', 'relaxation'],
  },
  {
    id: '4',
    title: 'Professional Game Development Workflow Tutorial',
    description: 'Learn the complete workflow of professional game developers. This tutorial covers project setup, asset creation, coding best practices, and optimization.',
    thumbnailUrl: 'https://images.pexels.com/photos/6068953/pexels-photo-6068953.jpeg',
    videoUrl: 'https://example.com/videos/game-dev-tutorial.mp4',
    duration: 2583, // 43:03
    views: 752318,
    likes: 42196,
    dislikes: 892,
    uploadDate: '2023-09-05',
    verified: true,
    channel: {
      id: 'c4',
      name: 'GameDev Pro',
      avatarUrl: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg',
      subscribers: 980000,
      verified: true,
    },
    category: 'Gaming',
    tags: ['game development', 'tutorial', 'Unity', 'coding'],
  },
  {
    id: '5',
    title: 'World News Recap: October 2023',
    description: 'A comprehensive recap of the major world events and news stories from October 2023, providing context and analysis on global developments.',
    thumbnailUrl: 'https://images.pexels.com/photos/518543/pexels-photo-518543.jpeg',
    videoUrl: 'https://example.com/videos/news-recap-oct.mp4',
    duration: 1489, // 24:49
    views: 425789,
    likes: 32156,
    dislikes: 4123,
    uploadDate: '2023-10-31',
    verified: true,
    channel: {
      id: 'c5',
      name: 'Global News Network',
      avatarUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
      subscribers: 5250000,
      verified: true,
    },
    category: 'News',
    tags: ['news', 'world events', 'politics', 'current affairs'],
  },
  {
    id: '6',
    title: 'Authentic Italian Pasta From Scratch',
    description: 'Learn how to make authentic Italian pasta from scratch with this step-by-step guide. From dough preparation to sauce pairing, become a pasta expert!',
    thumbnailUrl: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg',
    videoUrl: 'https://example.com/videos/italian-pasta.mp4',
    duration: 1845, // 30:45
    views: 876543,
    likes: 54321,
    dislikes: 987,
    uploadDate: '2023-06-18',
    verified: false,
    channel: {
      id: 'c6',
      name: 'Culinary Journeys',
      avatarUrl: 'https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg',
      subscribers: 1250000,
      verified: false,
    },
    category: 'Cooking',
    tags: ['cooking', 'pasta', 'Italian', 'food'],
  },
  {
    id: '7',
    title: 'Advanced React.js Patterns for Production',
    description: 'Discover advanced React.js patterns used in large-scale applications. This tutorial covers code organization, performance optimization, and state management.',
    thumbnailUrl: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg',
    videoUrl: 'https://example.com/videos/advanced-react.mp4',
    duration: 2745, // 45:45
    views: 632147,
    likes: 39875,
    dislikes: 753,
    uploadDate: '2023-04-25',
    verified: true,
    channel: {
      id: 'c7',
      name: 'WebDev Mastery',
      avatarUrl: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
      subscribers: 875000,
      verified: true,
    },
    category: 'Technology',
    tags: ['React', 'JavaScript', 'web development', 'programming'],
  },
  {
    id: '8',
    title: 'The Science of Sleep: How to Improve Your Rest',
    description: 'A scientific exploration of sleep cycles, how sleep affects health, and practical tips to improve sleep quality and duration.',
    thumbnailUrl: 'https://images.pexels.com/photos/1557238/pexels-photo-1557238.jpeg',
    videoUrl: 'https://example.com/videos/sleep-science.mp4',
    duration: 1685, // 28:05
    views: 985432,
    likes: 76123,
    dislikes: 1247,
    uploadDate: '2023-03-12',
    verified: true,
    channel: {
      id: 'c8',
      name: 'Health Decoded',
      avatarUrl: 'https://images.pexels.com/photos/1382731/pexels-photo-1382731.jpeg',
      subscribers: 2100000,
      verified: true,
    },
    category: 'Science',
    tags: ['sleep', 'health', 'science', 'wellness'],
  },
  {
    id: '9',
    title: 'Street Photography Masterclass',
    description: 'Master the art of street photography with this comprehensive guide covering gear selection, composition techniques, and editing workflows.',
    thumbnailUrl: 'https://images.pexels.com/photos/1509582/pexels-photo-1509582.jpeg',
    videoUrl: 'https://example.com/videos/street-photography.mp4',
    duration: 3245, // 54:05
    views: 378965,
    likes: 28764,
    dislikes: 631,
    uploadDate: '2023-02-28',
    verified: false,
    channel: {
      id: 'c9',
      name: 'Visual Artists',
      avatarUrl: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg',
      subscribers: 745000,
      verified: false,
    },
    category: 'Art',
    tags: ['photography', 'street', 'art', 'cameras'],
  },
  {
    id: '10',
    title: 'Hidden Gems: Unexplored Travel Destinations',
    description: 'Discover stunning travel destinations off the beaten path. This video showcases lesser-known locations with breathtaking scenery and authentic cultural experiences.',
    thumbnailUrl: 'https://images.pexels.com/photos/2161467/pexels-photo-2161467.jpeg',
    videoUrl: 'https://example.com/videos/hidden-travel-gems.mp4',
    duration: 1956, // 32:36
    views: 542786,
    likes: 47529,
    dislikes: 834,
    uploadDate: '2023-01-15',
    verified: true,
    channel: {
      id: 'c10',
      name: 'Wanderlust Adventures',
      avatarUrl: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
      subscribers: 1650000,
      verified: true,
    },
    category: 'Travel',
    tags: ['travel', 'destinations', 'adventure', 'tourism'],
  },
  {
    id: '11',
    title: 'NFL Season Highlights: Spectacular Plays',
    description: 'Relive the most spectacular plays from this NFL season. From incredible catches to game-changing touchdowns, witness the best moments in football.',
    thumbnailUrl: 'https://images.pexels.com/photos/163398/football-american-football-quarterback-runner-163398.jpeg',
    videoUrl: 'https://example.com/videos/nfl-highlights.mp4',
    duration: 1247, // 20:47
    views: 1247856,
    likes: 98745,
    dislikes: 2345,
    uploadDate: '2023-02-10',
    verified: true,
    channel: {
      id: 'c11',
      name: 'Sports Central',
      avatarUrl: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
      subscribers: 3250000,
      verified: true,
    },
    category: 'Sports',
    tags: ['NFL', 'football', 'sports', 'highlights'],
  },
  {
    id: '12',
    title: 'Fall Fashion Trends 2023: What\'s In Style',
    description: 'Explore the hottest fashion trends for fall 2023. From runway showcases to street style, learn how to incorporate these trends into your wardrobe.',
    thumbnailUrl: 'https://images.pexels.com/photos/2043590/pexels-photo-2043590.jpeg',
    videoUrl: 'https://example.com/videos/fashion-trends.mp4',
    duration: 1358, // 22:38
    views: 874569,
    likes: 72456,
    dislikes: 1234,
    uploadDate: '2023-08-30',
    verified: false,
    channel: {
      id: 'c12',
      name: 'Style Insider',
      avatarUrl: 'https://images.pexels.com/photos/1308885/pexels-photo-1308885.jpeg',
      subscribers: 925000,
      verified: false,
    },
    category: 'Fashion',
    tags: ['fashion', 'trends', 'style', 'fall', 'clothing'],
  },
];